import { Activity, BrainCircuit, CreditCard, FileDown, Gauge, Landmark, RefreshCw, UsersRound, WalletCards } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import {
  Area,
  AreaChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis
} from "recharts";
import { Panel } from "../components/Panel";
import { StatCard } from "../components/StatCard";
import { api, errorMessage } from "../lib/api";
import type { ExecutiveDashboard } from "../types";

export function ExecutivePage() {
  const [data, setData] = useState<ExecutiveDashboard | null>(null);
  const [error, setError] = useState("");

  async function load() {
    setError("");
    try {
      const response = await api.get("/dashboard/executive");
      setData(response.data);
    } catch (err) {
      setError(errorMessage(err));
    }
  }

  useEffect(() => { load(); }, []);

  const chartData = useMemo(
    () => data?.trends.map((item) => ({
      ...item,
      dateLabel: new Date(`${item.date}T00:00:00`).toLocaleDateString(undefined, { weekday: "short" }),
      volume: Number(item.volume)
    })) || [],
    [data]
  );

  function exportReport() {
    if (!data) return;
    const report = [
      "GLOBALPAY EXECUTIVE FINANCIAL OPERATIONS REPORT",
      `Generated: ${new Date().toISOString()}`,
      "",
      `Active customers: ${data.active_customers}`,
      `Digital wallets: ${data.digital_wallets}`,
      `Active merchants: ${data.active_merchants}`,
      `Payment count: ${data.payment_count}`,
      `Payment volume: ${data.payment_volume} PKR`,
      `Payment success rate: ${data.payment_success_rate}%`,
      `Open fraud alerts: ${data.open_fraud_alerts}`,
      `High-risk alerts: ${data.high_risk_alerts}`,
      `Open Banking API calls: ${data.api_calls}`,
      `CBDC wallets: ${data.cbdc_wallets}`,
      `CBDC transfer volume: ${data.cbdc_volume} ePKR`,
      "",
      "This report contains simulated data and is generated by a standards-aligned proof of concept."
    ].join("\n");
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `globalpay-executive-report-${new Date().toISOString().slice(0, 10)}.txt`;
    anchor.click();
    URL.revokeObjectURL(url);
  }

  return (
    <>
      <div className="page-title-row">
        <div><p className="eyebrow">Module 5</p><h2>Executive Financial Operations Dashboard</h2><p>Read-only aggregation of wallet, payment, fraud, API and CBDC performance.</p></div>
        <div className="button-row">
          <button className="secondary-button" onClick={load}><RefreshCw size={16} /> Refresh</button>
          <button className="primary-button" onClick={exportReport} disabled={!data}><FileDown size={16} /> Export report</button>
        </div>
      </div>
      {error && <div className="form-error">{error}</div>}

      <div className="stats-grid four">
        <StatCard label="Active customers" value={data?.active_customers ?? "—"} detail={`${data?.digital_wallets ?? "—"} wallets`} icon={UsersRound} tone="teal" />
        <StatCard label="Payment volume" value={data ? `${Number(data.payment_volume).toLocaleString()} PKR` : "—"} detail={`${data?.payment_success_rate ?? "—"}% success`} icon={CreditCard} tone="blue" />
        <StatCard label="Fraud alerts" value={data?.open_fraud_alerts ?? "—"} detail={`${data?.high_risk_alerts ?? "—"} high risk`} icon={BrainCircuit} tone="red" />
        <StatCard label="Open Banking calls" value={data?.api_calls ?? "—"} detail={`${data?.cbdc_wallets ?? "—"} CBDC wallets`} icon={Landmark} tone="violet" />
      </div>

      <div className="executive-layout">
        <Panel title="Seven-day payment trend" subtitle="Completed transaction volume and count" className="chart-panel">
          <div className="chart-container">
            <ResponsiveContainer width="100%" height={310}>
              <AreaChart data={chartData} margin={{ top: 12, right: 12, left: 0, bottom: 0 }}>
                <defs>
                  <linearGradient id="volumeFill" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#16b8a6" stopOpacity={0.4} />
                    <stop offset="95%" stopColor="#16b8a6" stopOpacity={0.02} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#dce7ee" vertical={false} />
                <XAxis dataKey="dateLabel" tickLine={false} axisLine={false} />
                <YAxis tickLine={false} axisLine={false} width={62} />
                <Tooltip formatter={(value) => `${Number(value).toLocaleString()} PKR`} />
                <Area type="monotone" dataKey="volume" stroke="#0d9488" fill="url(#volumeFill)" strokeWidth={3} />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </Panel>

        <Panel title="Cross-module pulse" subtitle="Current operational condition">
          <div className="pulse-list">
            <div><span className="pulse-icon teal"><WalletCards /></span><p><strong>Wallet ecosystem</strong><small>{data?.digital_wallets ?? "—"} wallets · {data?.active_merchants ?? "—"} active merchants</small></p></div>
            <div><span className="pulse-icon blue"><CreditCard /></span><p><strong>Payment operations</strong><small>{data?.payment_count ?? "—"} completed records</small></p></div>
            <div><span className="pulse-icon red"><BrainCircuit /></span><p><strong>Fraud operations</strong><small>{data?.open_fraud_alerts ?? "—"} alerts awaiting review</small></p></div>
            <div><span className="pulse-icon violet"><Landmark /></span><p><strong>Open finance</strong><small>{Number(data?.cbdc_volume || 0).toLocaleString()} ePKR transferred</small></p></div>
          </div>
        </Panel>
      </div>

      <div className="two-column">
        <Panel title="Governance controls" subtitle="Leadership visibility without operational write-back">
          <ul className="evidence-list">
            <li><Gauge /><div><strong>COBIT 2019</strong><span>Accountable KPIs, reporting and audit evidence</span></div></li>
            <li><Activity /><div><strong>NIST CSF 2.0</strong><span>Risk and operational visibility across the platform</span></div></li>
            <li><UsersRound /><div><strong>Least privilege</strong><span>Executive routes are read-only and role protected</span></div></li>
          </ul>
        </Panel>
        <Panel title="Decision summary" subtitle="Designed for executive and board-level discussion">
          <div className="decision-callout">
            <strong>{data?.payment_success_rate ?? 100}%</strong>
            <span>payment completion rate</span>
            <p>Review high-risk alerts and API health before expanding simulated transaction volume.</p>
          </div>
        </Panel>
      </div>
    </>
  );
}
